# Generated by Django 2.0.3 on 2018-10-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestingarea',
            old_name='graphic_provide',
            new_name='area_provide',
        ),
    ]
