# Generated by Django 2.0.3 on 2018-10-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181016_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestingarea',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
